New remove saved guides
GabrielModin/supportMe pull request #99
Opened 2021-05-16 15:04 UTC by Raion1

2021-05-16 19:58 UTC, nicholasnarvell approved these changes

2021-05-17 06:22 UTC, GabrielModin requested changes
Ser generellt :+1:  ut, user objekt ligger redan i connection och bör hämtas därifrån.

2021-05-17 06:22 UTC, GabrielModin commented on Code/ProjectMain/Client/src/main/java/org/supportmeinc/MainController.java
> +            guideManager = new GuideManager(connection, user);
Se kommentar i konstruktor

2021-05-17 06:22 UTC, GabrielModin commented on Code/ProjectMain/Client/src/main/java/org/supportmeinc/model/GuideManager.java
> +        connection.revokeAccess(id, user.getEmail());
Se kommentar i konstruktor.

2021-05-17 06:22 UTC, GabrielModin commented on Code/ProjectMain/Client/src/main/java/org/supportmeinc/model/GuideManager.java
> +        this.user = user;
User objekt finns redan i connection, instansvariabel i GudeManager är överflödig

2021-05-17 09:38 UTC, GabrielModin approved these changes
:+1:

2021-05-17 09:38 UTC, merged